
package net.jforum.dao.generic;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import net.jforum.JForumExecutionContext;
import net.jforum.entities.Smilie;
import net.jforum.exceptions.DatabaseException;
import net.jforum.util.DbUtils;
import net.jforum.util.preferences.SystemGlobals;

public class GenericSmilieDAO extends AutoKeys implements net.jforum.dao.SmilieDAO {

	public int addNew(Smilie smilie) {
		PreparedStatement p = null;
		try {
			p = this.getStatementForAutoKeys("SmiliesModel.addNew");
			p.setString(1, smilie.getCode());
			p.setString(2, smilie.getUrl());
			p.setString(3, smilie.getDiskName());
			setAutoGeneratedKeysQuery(SystemGlobals.getSql("SmiliesModel.lastGeneratedSmilieId"));
			return executeAutoKeysQuery(p);
		} catch (SQLException e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(p);
		}
	}

	public void delete(int id) {
		PreparedStatement p = null;
		try {
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.delete"));
			p.setInt(1, id);
			p.executeUpdate();
		} catch (SQLException e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(p);
		}
	}

	public void update(Smilie smilie) {
		PreparedStatement p = null;
		try {
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.update"));
			p.setString(1, smilie.getCode());
			p.setString(2, smilie.getUrl());
			p.setString(3, smilie.getDiskName());
			p.setInt(4, smilie.getId());
			p.executeUpdate();
		} catch (SQLException e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(p);
		}
	}

	private Smilie getSmilie(ResultSet rs) throws SQLException {
		Smilie s = new Smilie();
		s.setId(rs.getInt("smilie_id"));
		s.setCode(rs.getString("code"));
		s.setUrl(rs.getString("url"));
		s.setDiskName(rs.getString("disk_name"));
		return s;
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public List selectAll() {
		System.out.println("--> [GenericSmilieDAO.selectAll] ......");
		List l = new ArrayList();
		PreparedStatement p = null;
		ResultSet rs = null;
		try {
			System.out.println("INFOR: Calling SQL Query for 'SmiliesModel.selectAll' ...");
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.selectAll"));
			rs = p.executeQuery();
			while (rs.next()) {
				l.add(getSmilie(rs));
			}
			System.out.println("DEBUG: the number of SmiliesModel.selectAll = " + l.size());
			return l;
		} catch (SQLException e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(rs, p);
		}
	}

	public Smilie selectById(int id) {
		PreparedStatement p = null;
		ResultSet rs = null;
		try {
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.selectById"));
			p.setInt(1, id);
			Smilie s = new Smilie();
			rs = p.executeQuery();
			if (rs.next()) {
				s = getSmilie(rs);
			}
			return s;
		} catch (SQLException e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(rs, p);
		}
	}
}
