
package net.jforum.dao.generic;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

import net.jforum.JForumExecutionContext;
import net.jforum.dao.BanlistDAO;
import net.jforum.entities.Banlist;
import net.jforum.exceptions.DatabaseException;
import net.jforum.util.DbUtils;
import net.jforum.util.preferences.SystemGlobals;

public class GenericBanlistDAO extends AutoKeys implements BanlistDAO {

	public void delete(int banlistId) {
		PreparedStatement p = null;
		try {
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("BanlistModel.delete"));
			p.setInt(1, banlistId);
			p.executeUpdate();
		} catch (Exception e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(p);
		}
	}

	public void insert(Banlist b) {
		PreparedStatement p = null;
		try {
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("BanlistModel.insert"));
			p.setInt(1, b.getUserId());
			p.setString(2, b.getIp());
			p.setString(3, b.getEmail());
			setAutoGeneratedKeysQuery(SystemGlobals.getSql("BanlistModel.lastGeneratedBanlistId"));
			int id = executeAutoKeysQuery(p);
			b.setId(id);
		} catch (Exception e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(p);
		}
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public List selectAll() {
		System.out.println("--> [GenericBanlistDAO.selectAll] ......");
		ResultSet rs = null;
		PreparedStatement p = null;
		List l = new ArrayList();
		try {
			System.out.println("INFOR: Calling SQL Query for 'BanlistModel.selectAll' ...");
			p = JForumExecutionContext.getConnection().prepareStatement(SystemGlobals.getSql("BanlistModel.selectAll"));
			rs = p.executeQuery();
			while (rs.next()) {
				Banlist b = new Banlist();
				b.setId(rs.getInt("banlist_id"));
				b.setUserId(rs.getInt("user_id"));
				b.setEmail(rs.getString("banlist_email"));
				b.setIp(rs.getString("banlist_ip"));
				l.add(b);
			}
			System.out.println("DEBUG: the BanList.size() = " + l.size());
		} catch (Exception e) {
			throw new DatabaseException(e);
		} finally {
			DbUtils.close(rs, p);
		}
		return l;
	}
}
